# Site settings
title: PwzXxm
email: cepheidfov@gmail.com
description: Learning and sharing algorithms, computer science blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pwzxxm.com" # the base hostname & protocol for your site
github_username:  PwzXxm

gems:
- jekyll-multiple-languages
- jekyll-sitemap

# multi-lang
languages:          ['en', 'cn']
# If not config, the first of languages will be the default
language_default:   'en'
fill_default_content: true


# pagination
paginate: 10
paginate_limit: 5

# Build settings
markdown:  redcarpet-pygments
highlighter: pygments
permalink: /:title/
