# Site settings
title: PwzXxm
email: cepheidfov@gmail.com
description: ʕ •ᴥ•ʔ
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pwzxxm.com" # the base hostname & protocol for your site
github_username:  PwzXxm

# pagination
paginate: 8
paginate_limit: 4

# Build settings
markdown: kramdown
permalink: /:title/
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/zh
    values:
      layout: default
      lang: zh
