# Site settings
title: PwzXxm
email: cepheidfov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  blablabla
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pwzxxm.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  PwzXxm

# Build settings
markdown: kramdown
permalink: /:title/
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/zh
    values:
      layout: default
      lang: zh
