# Site settings
title: PwzXxm
email: cepheidfov@gmail.com
description: Learning and sharing computer science ideas. Enjoy what you are passionated about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.pwzxxm.com" # the base hostname & protocol for your site
github_username:  PwzXxm
exclude: ["README.md"]
gems:
- jekyll-multiple-languages
- jekyll-sitemap
- jekyll-paginate
- jemoji

# multi-lang
languages:          ['en', 'cn']
# If not config, the first of languages will be the default
language_default:   'en'
fill_default_content: true
sass:
    style: compressed

# pagination
paginate: 10

# Build settings
markdown:  redcarpet-pygments
# markdown:  redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink", "fenced_code_blocks", "with_toc_data"]
highlighter: pygments
permalink: /:title/
