source 'https://rubygems.org'
gem 'bundler','1.14.3'
gem 'execjs','2.6.0'
gem 'json', '1.8.3'
gem 'kramdown', '1.5.0'
gem 'yajl-ruby', '1.2.1'
gem 'pygments.rb','0.6.3'
gem 'redcarpet', '3.3.2'
gem 'github-pages', '39', group: :jekyll_plugins
gem 'jekyll-multiple-languages', '1.0.11'
gem 'jekyll-sitemap', '0.8.1'
gem 'rouge'
